#!/bin/sh

PIDF=/var/run/ai_monitor_all.pid
if [ -e $PIDF ]; then
	PID=$(cat $PIDF)
	SID=$(awk '{ print $6 }' /proc/$PID/stat)
	PID2=$(awk '{ print $1 }' /proc/$PID/stat)
	if [ $PID -eq $PID2 -a $PID -eq $SID ]; then
		echo SANITY check: PID: $PID PID2 $PID2 SID $SID ALL GOOD kill SID and hide the body
		pkill -s $SID
		rm $PIDF
	else
		echo SANITY check: PID: $PID PID2 $PID2 SID $SID FAIL
		exit 1;
	fi
fi


for SX in /dev/acq420.?
do
	SITE=${SX#*.}
	OPTS=""
	DATA32=$(cat $SX.knobs/data32)
	if [ $DATA32 -eq 1 ]; then
		OPTS="-w 4"
	fi	
	acq400_stream $OPTS --hb0 $SITE 2>&1 >/dev/null &
done
	
	
forsleep update-histo 2>&1 >/dev/null &

