#!/bin/sh

PIDF=/var/run/ai_monitor_all.pid
LOG=/var/log/ai_monitor.log

start() {
	/usr/local/bin/procServ \
		-c / -p ${PIDF} -L $LOG \
		2223 \
	/usr/local/bin/ai_monitor_all run_monitor
}

stop() {
        if [ -r ${PIDF} ]; then
                kill -s TERM $(cat ${PIDF})
                rm ${PIDF}
        fi
}

link_aggregator_sites() 
{
	ASITES=$(awk '{ print $2 }' </etc/acq400/0/aggregator | tr ,  \  | sed -e s/=/=\"/ -e s/\$/\"/)
	let ACH=1
	eval $ASITES
	for site in $sites
	do
		TWF=/dev/shm/AI.$site.wf
		echo mkdir $TWF
		mkdir $TWF

		for ch in $(seq 1 $(cat /dev/acq400.$site.knobs/active_chan))
		do
			ln -s /dev/shm/AI.0.wf/$(printf "CH%02d" $ACH) $TWF/$(printf "CH%02d" $ch)
			let ACH=$ACH+1
		done
	done
}

run_monitor() {
	for SX in /dev/acq400.?
	do
		SITE=${SX#*.}
		OPTS=""
		DATA32=$(cat $SX.knobs/data32)
		if [ $DATA32 -eq 1 ]; then
			OPTS="-w 4"
		fi
		NCFILE=/etc/acq400/$SITE/NCHAN
		NCHAN=0
		if [ -e $NCFILE ]; then
			NCHAN=$(cat $NCFILE)
			OPTS="$OPTS --nchan $NCHAN"
		fi	
		/usr/local/bin/acq400_stream $OPTS --hb0 $SITE &

		if [ $SITE -eq 0 ] && [ $NCHAN -gt 0 ]; then
			link_aggregator_sites
			break
		fi
	done
	
	forsleep update-histo 2>&1 >/dev/null &
	wait;wait;wait
}

trap "pkill -s 0" SIGINT SIGTERM

case "$1" in
run_monitor)
	run_monitor;;
start)
	stop; start;;
stop)
	stop;;
esac


