#!/bin/sh

PIDF=/var/run/ai_monitor_all.pid
LOG=/var/log/ai_monitor.log

VERBOSE=${VERBOSE:-0}

start() {
	/usr/local/bin/procServ \
		-c / -p ${PIDF} -L $LOG \
		2223 \
	/usr/local/bin/ai_monitor_all run_monitor
}

stop() {
        if [ -r ${PIDF} ]; then
                kill -s TERM $(cat ${PIDF})
                rm ${PIDF}
        fi
}

ONDEMUX_COMPLETE=/tmp/ondemux_complete


make_ondemux_complete() {
cat - >$ONDEMUX_COMPLETE <<EOF
#!/bin/sh
for s in $*
do
	date > /dev/shm/AI.\$s.wf.fin
done
EOF
chmod a+rx $ONDEMUX_COMPLETE
}



link_aggregator_sites() 
{
	ASITES=$(awk '{ print $2 }' </etc/acq400/0/aggregator | tr ,  \  | sed -e s/=/=\"/ -e s/\$/\"/)
	let ACH=1
	eval $ASITES
	make_ondemux_complete $sites

	for site in $sites
	do
		TWF=/dev/shm/AI.$site.wf
		[ -d $TWF ] || mkdir $TWF

		for ch in $(seq 1 $(cat /dev/acq400.$site.knobs/active_chan))
		do
			lhs=/dev/shm/AI.0.wf/$(printf "CH%02d" $ACH)
			rhs=$TWF/$(printf "CH%02d" $ch)
			[ -L $rhs ] || ln -s $lhs $rhs
			let ACH=$ACH+1
		done
	done
}

run_monitor() {
	for SX in /dev/acq400.?
	do
		SITE=${SX#*.}
		OPTS="--verbose $VERBOSE "
		DATA32=$(cat /etc/acq400/$SITE/data32)
		if [ $DATA32 -eq 1 ]; then
			OPTS="$OPTS -w 4"
		fi
		NCFILE=/etc/acq400/$SITE/NCHAN
		NCHAN=0
		if [ -e $NCFILE ]; then
			NCHAN=$(cat $NCFILE)
			OPTS="$OPTS --nchan $NCHAN"
		fi	
		if [ $SITE -eq 0 ] && [ $NCHAN -gt 0 ]; then
			link_aggregator_sites
			OPTS="$OPTS --oncompletion $ONDEMUX_COMPLETE"
		fi

		echo run /usr/local/bin/acq400_stream $OPTS --hb0 $SITE
		/usr/local/bin/acq400_stream $OPTS --hb0 $SITE &

		if [ $SITE -eq 0 ] && [ $NCHAN -gt 0 ]; then
			break
		fi
	done
	
	forsleep update-histo 2>&1 >/dev/null &
	wait;wait;wait
}

trap "pkill -s 0" SIGINT SIGTERM

case "$1" in
run_monitor)
	run_monitor;;
start)
	stop; start;;
stop)
	stop;;
esac


