#!/bin/sh

ETOP=/usr/local/epics
STCMD=/tmp/st.cmd
PIDF=/var/run/acq400ioc.pid
LOG=/var/log/epics.log

if [ -f /etc/profile.d/epics.sh ]; then
	source /etc/profile.d/epics.sh
fi

make_stcmd() {
	if [ ! -e ${STCMD} ]; then
		(cd ${ETOP}
		./scripts/load.records >${STCMD})
		touch /dev/shm/AI
		
		ai_monitor_all start
	fi
}

start_ioc() {
	/usr/local/bin/procServ \
		-c ${ETOP} -p $PIDF -L $LOG \
		2222 \
	/usr/local/bin/acq400ioc ${STCMD}
}

stop_ioc() {
	if [ -r ${PIDF} ]; then
		kill -s TERM $(cat ${PIDF})
		rm ${PIDF}
	fi
}

restart() {
	if [ "$1" = "force" ]; then
		rm -f ${STCMD}
	fi	
	make_stcmd
	stop_ioc
	start_ioc
}

case "$1" in
forcestart)
	restart force;;
start|"")
	restart;;
stop)
	stop_ioc;;

*)
	echo usage acq400ioc.init start\|stop\|forcestart;;
esac
