#!/bin/bash
# copy library and headers from source package location.

mkdir -p lib/linux-arm lib/linux-x86_64/ include
cp -a ../lib/linux-arm/libacq.so* lib/linux-arm
cp -a ../lib/linux-x86_64/libacq.so* lib/linux-x86_64/
cp -a ../include/* include

