#!/bin/bash
# copy library and headers from source package location.

cp -a ../lib/linux-arm/libacq.so* lib/linux-arm
cp -a ../lib/linux-x86_64/libacq.so* lib/linux-x86_64/
cp ../ACQ420FMC/acq-util.h include
cp ../ACQ420FMC/Buffer.h include
cp ../ACQ420FMC/ES.h include

