#!/bin/sh
# configure clocking with acq1014 and acq480
# local (clk-trg-star 20M) :
# acq1014+acq480.init Fsample
# front panel clk (fpclk)
# acq1014+acq480.init fpclk Fsys Fsample
# Defaults: Fsys=20MHz, Fsample=50MHz

cp /usr/local/CARE/acq480_streamd.0.conf /etc/sysconfig/acq400_streamd.0.conf

init_mb_clk() {
	/usr/local/epics/scripts/wait_ioc_ready
	sleep 1
	set.site 0 SYS:CLK:FPMUX=FPCLK
	set.site 0 SIG:CLK_MB:FIN=20000000
	set.site 0 SIG:CLK_MB:SET $1
	set.site 1 clk=1,1,1
	set.site 1 trg=1,0,0
}

(init_mb_clk ${1:-50000000}) & 
