#!/bin/sh
# configure clocking with acq1001 and acq4
# local (zclk) :
# acq1001+acq424.init FCLK CLKDIV
# Default : FCLK=16M, CLDIV=16
# front panel clk (fpclk)
# acq1001+acq424.init fpclk Fsys FCLK CLKDIV
# Defaults: Fsys=1MHz, FCLK=16MHz CLKDIV=16MHz

cp /usr/local/CARE/acq480_streamd.0.conf /etc/sysconfig/acq400_streamd.0.conf

init_mb_clk() {
	/usr/local/epics/scripts/wait_ioc_ready
	set.site 1 clk=1,1,0
	sleep 1
	set.site 0 SIG:ZCLK_SRC=INT33M
	set.site 0 SYS:CLK:FPMUX=ZCLK
	set.site 0 SIG:CLK_MB:FIN=33333000
	set.site 0 SIG:CLK_MB:SET $1
	set.site 1 CLKDIV=$2
}

init_mb_clk_fp() {
	/usr/local/epics/scripts/wait_ioc_ready
	set.site 1 clk=1,1,0
	sleep 1
	set.site 0 SYS:CLK:FPMUX=FPCLK
	set.site 0 SIG:CLK_MB:FIN=$1
	set.site 0 SIG:CLK_MB:SET $2
	set.site 1 CLKDIV=$3
}

case $1 in
fpclk)
	# FP_CLK, 1MHz multiply to 16MHz, CLKDIV=16 => 1MHz
	(init_mb_clk_fp ${2:-1000000} ${3:-16000000} ${4:-16}) & 
	;;
*)
	# MB_CLK, 16MHz / 16 = 1MHz
	(init_mb_clk ${1:-16000000} ${2:-16}) &
	;;
esac



