#!/bin/sh
# configure clocking with acq1001 and acq43x

cp /usr/local/CARE/acq400_streamd.0.conf-soft_trigger \
	/etc/sysconfig/acq400_streamd.0.conf


init_mb_clk() {
		/usr/local/epics/scripts/wait_ioc_ready
		set.site 0 SYS:CLK:FPMUX=XCLK
		set.site 0 SIG:CLK_MB:FIN=32768000
		set.site 0 SYS:CLK:OE_CLK1_ZYNQ 1
		set.site 1 ACQ43X_SAMPLE_RATE=$1
		set.site 0 SYS:CLK:OE_CLK1_ZYNQ 1
}

init_mb_clk_fp() {
		/usr/local/epics/scripts/wait_ioc_ready
		set.site 0 SIG:CLK_MB:FIN=$1    
		set.site 0 SYS:CLK:FPMUX=FPCLK
		set.site 0 SYS:CLK:OE_CLK1_ZYNQ 1
		set.site 1 ACQ43X_SAMPLE_RATE=$2
}

case $1 in
fpclk)
       (init_mb_clk_fp ${2:-1000000} ${3:-37000}) &
       ;;
*)
       (init_mb_clk ${1:-37000}) &
       ;;
esac
