#!/bin/sh
# configure clocking with acq2106 and acq42x
# since Si5326 can generate a high quality clock anywhere from 2k to 100M,
# let's use it, set CLKDIV to 1 ALWAYS.

cp /usr/local/CARE/acq400_streamd.0.conf-soft_trigger \
        /etc/sysconfig/acq400_streamd.0.conf

init_common() {
    	set.site 0 SYS:CLK:BYPASS=0
		set.site 0 SYS:CLK:DIST_CLK_SRC Si5326
		set.site 0 SYS:CLK:OE_CLK1_ZYNQ=1
		set.site 0 SIG:SRC:CLK:1=MCLK

}
init_mb_clk() {
    	/usr/local/epics/scripts/wait_ioc_ready
    	set.site 1 'CLK=1; CLK:DX=d1; CLK:SENSE=falling'        
        init_common
        set.site 0 SIG:ZCLK_SRC=INT33M
        set.site 0 SYS:CLK:FPMUX=ZCLK
        set.site 0 SIG:CLK_MB:FIN=33333000
        set.site 0 SIG:CLK_MB:SET=$1
        set.site 1 CLKDIV=1
}

init_mb_clk_fp() {
        /usr/local/epics/scripts/wait_ioc_ready
        set.site 1 'CLK=1; CLK:DX=d1; CLK:SENSE=falling'
        init_common
        set.site 0 SYS:CLK:FPMUX=FPCLK
        set.site 0 SIG:CLK_MB:FIN=$1
        set.site 0 SIG:CLK_MB:SET=$2
        set.site 1 CLKDIV=1
}

case $1 in
fpclk)
        # FP_CLK, 1MHz multiply to 1MHz, => 1MHz
        (init_mb_clk_fp ${2:-1000000} ${3:-1000000}) &
        ;;
*)
        # MB_CLK, 1MHz = 1MHz
        (init_mb_clk ${1:-1000000} ) &
        ;;
esac



