#!/bin/sh

set_master() {
	echo set_master
	set.site 0 SIG:SYNC_OUT:CLK CLK
	set.site 0 SIG:SYNC_OUT:CLK:DX d1
	set.site 0 SIG:SYNC_OUT:TRG TRG
	set.site 0 SIG:SYNC_OUT:TRG:DX d0
}

set_slave() {
	echo set_slave
	set_master
	set.site 0 SIG:SRC:CLK:1 HDMI
	set.site 0 SIG:SRC:TRG:0 HDMI
	set.site 0 SYS:CLK:DIST_CLK_SRC HDMI
}

set_fpmaster() {
        set.site 0 SYS:CLK:FPMUX FPCLK
        set.site 0 SYS:CLK:BYPASS 1
        set.site 0 SYS:CLK:DIST_CLK_SRC Si5326
        set.site 0 SYS:CLK:OE_CLK1_ZYNQ 1
        set.site 0 SIG:SRC:CLK:1 MCLK
}

case $1 in
fpmaster)
	(/usr/local/epics/scripts/wait_ioc_ready; sleep 2
        set_master; set_fpmaster) & ;;
master)
	(/usr/local/epics/scripts/wait_ioc_ready; sleep 2
	set_master) & ;;
slave)
	(/usr/local/epics/scripts/wait_ioc_ready; sleep 2
	set_slave) & ;;
*)
	echo "USAGE set_acq2106-hdmi-acq42x-routing master\|slave";;
esac

