#!/bin/sh

set_master() {
	echo set_master
	set.site 1 SIG:SYNC_OUT:CLK CLK
	set.site 0 SIG:SYNC_OUT:CLK:DX d1
	set.site 0 SIG:SYNC_OUT:TRG TRG
	set.site 0 SIG:SYNC_OUT:TRG:DX d0
}

set_slave() {
	echo set_slave
	set_master
	
}

case $1 in
master)
	set_master;;
slave)
	set_slave;;
*)
	echo "USAGE set_acq2106-hdmi-acq42x-routing master\|slave";;
esac

