#!/bin/sh

set_master() {
	echo set_master
	set.site 0 SIG:SYNC_OUT:CLK CLK
	set.site 0 SIG:SYNC_OUT:CLK:DX d1
	set.site 0 SIG:SYNC_OUT:TRG TRG
	set.site 0 SIG:SYNC_OUT:TRG:DX d0
}

set_slave() {
	echo set_slave
	set_master
	set.site 0 SIG:SRC:CLK:1 HDMI
	set.site 0 SIG:SRC:TRG:0 HDMI
	set.site 0 SYS:CLK:DIST_CLK_SRC HDMI
}

case $1 in
master)
	(/usr/local/epics/scripts/wait_ioc_ready; sleep 2
	set_master) & ;;
slave)
	(/usr/local/epics/scripts/wait_ioc_ready; sleep 2
	set_slave) & ;;
*)
	echo "USAGE set_acq2106-hdmi-acq42x-routing master\|slave";;
esac

