#!/bin/sh

DIV=${1:-10}

set.site 0 SIG:ZCLK_SRC INT33M
set.site 0 SYS:CLK:FPMUX ZCLK
set.site 0 SYS:CLK:BYPASS 0
set.site 0 SYS:CLK:OE_CLK1_ZYNQ 1
load.si5326 /etc/si5326.d/si5326_33M333-10M.txt
set.site 1 CLKDIV=$DIV
set.site 1 clk=1,1,1
