#!/bin/sh

bit=${1:0}
val=${2}

# acq1001_389:2:COS:EN:L16.B0

if [ $(($bit/16)) -eq 0 ]; then
	hl=L16
else
	hl=H16
fi
bx=B$(($bit%16))
HN=$(hostname)
PV=${HN}:${SITE}:COS:EN:${hl}.${bx}

export EPICS_CA_AUTO_ADDR_LIST=NO EPICS_CA_ADDR_LIST=127.0.0.1

[ -z "$val" ] && echo VAL is Z

if [ -z "$val" ]; then                                                                         
	VALUE=$(caget -ts ${PV})                                                                        
        if [ $? -eq 0 ]; then                                                                          
       		echo ${VALUE#${PV}:}                                                     
        else                                                                       
        	echo ${VALUE}                                                                  
        fi                                                                              
else                                                                                             
        caput ${PV} $val                                                                    
        if [ $? -ne 0 ]; then                                                                          
                echo ERROR                                                                             
        fi                                                                                             
fi      
