#!/bin/sh

S1=${1:-1}

PVI=$(hostname):$S1:IMM:DI
PVO=$(hostname):$S1:IMM:DO

echo "loopback test to self, SITE=$S1 cabled d0-d15 => d16->d31"

/usr/local/CARE/dio432init.immediate $S1 1,1,0,0
sleep 1

for BYTE in 1 2; do
   for BIT in 0 1 2 3 4 5 6 7; do
	OUT=$(caput $PVO:BYTE$BYTE.B$BIT 1|grep New)
	sleep .2
	echo $OUT ' => ' $(caget $PVI:BYTE$((2+$BYTE)).B$BIT)
	caput $PVO:BYTE$BYTE.B$BIT 0 2>&1 >/dev/null
   done
done


