#!/bin/sh

extract_gains() 
{
   gains="$(xml_lookup  -c $1/caldef.xml ACQ.AcqCalibration.Data.@ranges 2>/dev/null)"
   if [ "x$gains" != "x" ]; then
       echo site $(basename $1) custom gains $gains
       echo "GAINS=$gains" > $1/gains.sh
   fi   
}

for s in /dev/sites/*
do
    if [ -e $s/caldef.xml ] && [ ! -e $s/gain.sh ]; then
        extract_gains $s
    fi
done