#!/bin/sh

set +e

while [ -z $IOC_HOST ]; do
	while [ ! -e /etc/profile.d/epics.sh ]; do
		sleep 1
	done
	source /etc/profile.d/epics.sh
done
PV=${IOC_HOST}:IOC_READY

RDY=""

while [ "x$RDY" != "x1" ]; do
	echo wait_ioc_ready $PV
	RDY=$(caget -nt $PV)
done

echo $PV all good now $RDY

