#!/bin/sh

set +e

[ -e /dev/shm/ioc_ready ] && exit 0

while [ -z $IOC_HOST ]; do
	while [ ! -e /etc/profile.d/epics.sh ]; do
		sleep 1
	done
	source /etc/profile.d/epics.sh
done

export EPICS_CA_AUTO_ADDR_LIST=NO EPICS_CA_ADDR_LIST=127.0.0.1
PV=${IOC_HOST}:IOC_READY

RDY=$(caget -nt $PV)

while [ "x$RDY" != "x1" ]; do
	echo wait_ioc_ready $PV
	sleep 1
	RDY=$(caget -nt $PV)
done

UPTIME=$(cat /proc/uptime | awk '{ print $1 }')

echo "UPTIME $UPTIME $PV all good now $RDY"
echo "UPTIME $UPTIME $PV all good now $RDY" >/dev/shm/ioc_ready

