#!/bin/sh

set +e

[ -e /dev/shm/ioc_ready ] && exit 0

while [ -z $IOC_HOST ]; do
	while [ ! -e /etc/profile.d/epics.sh ]; do
		sleep 1
	done
	source /etc/profile.d/epics.sh
done
PV=${IOC_HOST}:IOC_READY

RDY=""

while [ "x$RDY" != "x1" ]; do
	echo wait_ioc_ready $PV
	RDY=$(caget -nt $PV)
done

UPTIME=$(cat /proc/uptime | awk '{ print $1 }')

echo "UPTIME $UPTIME $PV all good now $RDY"
echo "UPTIME $UPTIME $PV all good now $RDY" >/dev/shm/ioc_ready

