#!/bin/sh

UUT=${UUT:-$(hostname)}
ABO=${ABO:-0}
TRG=${TRG:-1}

if [ -z $1 ]; then
	echo zapper $(caget "${UUT}:1:SHOT") TRG:$TRG ABO:$ABO

	caput "${UUT}:MODE:TRANSIENT:PRE" 		0
	caput "${UUT}:MODE:TRANSIENT:POST" 		5242
	caput "${UUT}:MODE:TRANSIENT:SOFT_TRIGGER"	0
	caput "${UUT}:MODE:TRANSIENT"		 	1
	# disable AUTO_SOFT_TRIGGER, but select soft trigger source
	set.site 1 trg=1,1,1
	caput "${UUT}:MODE:TRANSIENT:SET_ARM"		1

	state=$(caget -t ${UUT}:MODE:TRANS_ACT:STATE)
	echo $state
	while [ "$state" != "ARM" ]; do
		usleep 100000
		state=$(caget -t ${UUT}:MODE:TRANS_ACT:STATE)
		echo $state
	done

	[ $TRG -eq 1 ] && soft_trigger

	[ $ABO -eq 1 ] && caput "${UUT}:MODE:TRANSIENT:SET_ABORT" 1


	while [ "$state" != "IDLE" ]; do
		usleep 100000
		state=$(caget -t ${UUT}:MODE:TRANS_ACT:STATE)
		echo $state
	done
	echo "$state $(caget ${UUT}:MODE:TRANS_ACT:POST)"
else
	echo supervisor loop $0 ${1}
	for s in $(seq $1); do
		TRG=1 $0
		ABO=1 $0
	done
fi
